#???
server:
  port: 8088
#????????
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mytool?useUnicode=true&useSSL=false&characterEncoding=utf8
    username: root
    password: root
mybatis:
  #???????
  configuration:
    map-underscore-to-camel-case: true
mybatis-plus:
  # xml??
  mapper-locations: classpath:mapper/*Mapper.xml
  # ???????package?????????
  type-aliases-package: com.example.springbootdome.entity  #????????
  configuration:
    # ?????????sql?????????????????
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl